name: Greetings

# on: worworkflow_dispatch:
on: 
  workflow_dispatch:

  schedule:
  - cron: "* * * * * *"
jobs:
  status:
    name: Server Status
    runs-on: ubuntu-24.04
    steps: 
      - id: 1
        name: start: 
        run: 'ping 1.1.1.1 >> ~/ping.log'
# jobs: []
  # greeting:
    # runs-on: ubuntu-latest
    # run: ''
    # permissions:
    #   issues: write
    #   pull-requests: write
    # steps:
    # - uses: actions/first-interaction@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     issue-message: "Message that will be displayed on users' first issue"
    #     pr-message: "Message that will be displayed on users' first pull request"
