name: Greetings

# on: worworkflow_dispatch:
on: 
  workworkflow_run:
    app
jobs:
  greeting:
    runs-on: ubuntu-latest
    run: |
      echo "WG_IP"
    # permissions:
    #   issues: write
    #   pull-requests: write
    # steps:
    # - uses: actions/first-interaction@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     issue-message: "Message that will be displayed on users' first issue"
    #     pr-message: "Message that will be displayed on users' first pull request"
